### ISSUE TITLE
min/max incorrect behaviour?

### ISSUE THREAD

**Issue by jariberi** [vaadin/vaadin-date-picker#547]
### Description
Styles are wrong on month, when chenges min and max.

### Expected outcome
When min="2018-05-02" and max "2018-05-09" all May should be black (not grey) same as min="2018-05-01"

### Actual outcome
All May is grey.

### Live Demo
![date-picker-grey](https://user-images.githubusercontent.com/10248677/39541226-7c6126b2-4e1b-11e8-80b4-6a83a4dfaabc.gif)

**Comment by limonte** [comment]
Thanks for reporting @jariberi 

It's the theming issue, disabled days aren't styled properly. Looks critical to me, moving to the issue backlog.

**Comment by limonte** [comment]
Fixed in v3.0.1, thanks for reporting @jariberi!

**Comment by jariberi** [comment]
@limonte, the issue still exists in v3.0.1. 

```css
/* Disabled */

:host([disabled]) * {
    color: var(--lumo-disabled-text-color) !important;
}
```

The !important CSS rule is in html file, when I remove that, it works perfectly.
