### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-date-picker#683]
`vaadin-date-picker` invalid cannot be set initially. `invalid` message is just blinking on reload.

Example used:
`<vaadin-date-picker label="Date" invalid error-message="Invalid"></vaadin-date-picker>`

Can be reproduced on custom field `alignment` visual tests:

![date-picker](https://user-images.githubusercontent.com/29372419/66919279-b73c0480-f029-11e9-85fd-b91853c04ba8.gif)

**Comment by Haprog** [comment]
Looks like https://github.com/vaadin/vaadin-text-field/issues/417 which should be fixed in `vaadin-text-field`: v2.4.12, v2.5.0-alpha2, v2.6.0-alpha1

**Comment by Haprog** [comment]
Does this still happen here if using `vaadin-text-field ` v2.4.12 ?

**Comment by yuriy-fix** [comment]
Yeap, it is still happening. 
There is already a fix for this one by @web-padawan: https://github.com/vaadin/vaadin-date-picker/pull/684

**Comment by Haprog** [comment]
Closing as fixed (since `vaadin-date-picker` [v4.0.5](https://github.com/vaadin/vaadin-date-picker/releases/tag/v4.0.5)). Verified working in custom-field visual tests again.
